default:
  URL_MARKDOWN: "https://raw.githubusercontent.com/jduijvenbode-WWF/ForestForesight/main/README.md"
  AWS_BUCKET_NAME: "forestforesight-public"
  AWS_BUCKET_REGION: "eu-west-1"
  EARLIEST_DATA_DATE: "2021-01-01"
  DEFAULT_GROUNDTRUTH: "groundtruth1m"
  DATA_FOLDER: "C:/Kodingan3/FFdata/"
  TEST_FF_PREP_DATA: "C:/Kodingan3/FFdata/preprocessed"
  TEST_FF_PREP_QC_DATE: "2023-01-01"

test:
  URL_MARKDOWN: "https://raw.githubusercontent.com/jduijvenbode-WWF/ForestForesight/main/README.md"
  AWS_BUCKET_NAME: "forestforesight-public"
  AWS_BUCKET_REGION: "eu-west-1"
  EARLIEST_DATA_DATE: "2021-01-01"
  DEFAULT_GROUNDTRUTH: "groundtruth2m"
  DATA_FOLDER: "C:/Kodingan3/FFdata/"
  TEST_FF_PREP_DATA: "C:/Kodingan3/FFdata/preprocessed"
  TEST_FF_PREP_QC_DATE: "2023-01-01"
