name: R

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  Building-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.1.1']
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Install R dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("r-lib/rcmdcheck")
        shell: Rscript {0}
      - name: Session info
        run: sessionInfo()
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}