name: R

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  Building-package:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, r-version: '4.1.1' }
          - { os: macOS-latest, r-version: '4.1.1' }
          - { os: windows-latest, r-version: '4.1.1' }
    steps:
      - uses: actions/checkout@v2

      - name: Set up R ${{ matrix.config.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r-version }}

      - name: Install system dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev        
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev libfreetype6-dev
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev
          sudo apt-get install -y pkg-config

      - name: Set up GitHub PAT
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
        run: |
          gitcreds::gitcreds_set()

      - name: Install R dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("r-lib/rcmdcheck")
        shell: Rscript {0}
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      - name: Session info
        run: sessionInfo()
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
