name: R

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  Building-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.1'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev        
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev libfreetype6-dev
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev
          sudo apt-get install -y pkg-config

      - name: Install R dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Session info
        run: sessionInfo()
        shell: Rscript {0}

      - name: Build package
        run: |
          R CMD build . --no-build-vignettes --no-manual
        shell: bash

      - name: Check build directory (post-build)
        run: |
          echo "Checking current directory after build:"
          ls -l .
          echo "Checking parent directory after build:"
          ls -l ..
        shell: bash
        
      - name: Verify package tarball exists
        id: verify_tarball
        run: |
          tarball=$(ls ./ForestForesight_*.tar.gz)
          if [ -f "$tarball" ]; then
            echo "Package tarball found: $tarball"
            echo "TARBALL_PATH=$tarball" >> $GITHUB_ENV
          else
            echo "Package tarball NOT found!"
            exit 1
          fi
        shell: bash

      # Define a dynamic version number based on the run number
      - name: Set dynamic version number
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash
        
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ForestForesight ${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload package release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.TARBALL_PATH }}
          asset_name: ForestForesight_${{ env.VERSION }}.tar.gz
          asset_content_type: application/gzip

      - name: Final directory listing (post-upload)
        run: |
          echo "Final check of directories:"
          ls -l .
          ls -l ..
        shell: bash