name: R

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  Building-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.1'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev        
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev libfreetype6-dev
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev
          sudo apt-get install -y pkg-config

      - name: Install R dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Session info
        run: sessionInfo()
        shell: Rscript {0}

      - name: Build package
        run: |
          R CMD build . --no-build-vignettes --no-manual
        shell: bash

      - name: Check build directory (post-build)
        run: |
          echo "Checking current directory after build:"
          ls -l .
          echo "Checking parent directory after build:"
          ls -l ..
        shell: bash

      - name: Verify package tarball exists
        run: |
          if [ -f ./ForestForesight_*.tar.gz ]; then
            echo "Package tarball found."
          else
            echo "Package tarball NOT found!"
            exit 1
          fi
        shell: bash

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v4.0.0
          release_name: ForestForesight 4.0.0
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass the GitHub token here

      - name: Upload package release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ForestForesight_*.tar.gz
          asset_name: ForestForesight_4.0.0.tar.gz
          asset_content_type: application/gzip

      - name: Final directory listing (post-upload)
        run: |
          echo "Final check of directories:"
          ls -l .
          ls -l ..
        shell: bash