name: R Checks (no build yet)
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  Checking-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up R environment and install required system dependencies
      run: |
        sudo apt install libcurl4-openssl-dev  # Required for renv installation

    - name: Set up R environment and install R packages
      run: |
        mkdir -p ~/R/x86_64-pc-linux-gnu-library
        chmod 777 ~/R/x86_64-pc-linux-gnu-library
        # set library path
        libpath <- "~/R/x86_64-pc-linux-gnu-library"
        Rscript -e ".libPaths(libpath); install.packages(c('lintr', 'testthat', 'renv'), repos = 'https://cran.rstudio.com/')"

    - name: Run Linter
      run: |
          Rscript -e ".libPaths(libpath); lintr::lint()"

    - name: Initialize renv
      run: |
        Rscript -e ".libPaths(libpath); renv::init()"
    
    - name: Show installed R packages
      run: |
        Rscript -e ".libPaths(libpath); installed <- installed.packages(); print(installed[,c('Package', 'Version')])"

    - name: Run Tests
      run: |
        Rscript -e ".libPaths(libpath); testthat::test_dir()"