name: R Build and Checks
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        Rscript -e "install.packages(c('lintr', 'testthat'), repos = 'https://cran.rstudio.com/')"

    - name: Run Linter
      run: |
        Rscript -e "lintr::lint()"

    - name: Run Tests
      run: |
        Rscript -e "testthat::test_dir()"