name: R Checks (no build yet)
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  lintr-and-testthat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.2
    
    - name: Set up R environment and install required system dependencies
      run: |
        sudo apt install libcurl4-openssl-dev  # Required for renv installation

    - name: Set up R environment and install R packages
      run: |
        mkdir -p ~/R/x86_64-pc-linux-gnu-library
        chmod 777 ~/R/x86_64-pc-linux-gnu-library
        Rscript -e ".libPaths('~/R/x86_64-pc-linux-gnu-library'); install.packages(c('lintr', 'testthat'), repos = 'https://cran.rstudio.com/')"
    
    - name: Initialize renv
      run: |
        Rscript -e "renv::init()"
        
    - name: Run Linter
      run: |
        Rscript -e "lintr::lint()"

    - name: Run Tests
      run: |
        Rscript -e "testthat::test_dir()"