name: R Checks (no build yet)
on:
  pull_request:
    branches: [ "develop" ]

jobs:
  Checking-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
        sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev

    - name: Set up R environment
      uses: r-lib/actions/setup-r@v2

    - name: Caching - hope this can improve GitHub Action runtime
      uses: actions/cache@v3
      with:
        path: ~/.cache/R/  # Cache the R library cache
        key: ${{ runner.os }}-r-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Create R library directory
      run: mkdir -p ~/R

    - name: Install and run Linter
      run: |
        Rscript -e "install.packages('lintr', repos = 'https://cran.rstudio.com/', lib = '~/R'); library(lintr, lib.loc = '~/R'); lintr::lint_package()"

    - name: Install basic R packages
      run: |
        Rscript -e "install.packages(c('renv', 'devtools', 'testthat'), repos = 'https://cran.rstudio.com/', lib = '~/R')"

    - name: Initialize renv / installing packages in DESCRIPTION file
      run: |
        Rscript -e "renv::init()"

    - name: Show installed R packages
      run: |
        Rscript -e "renv::status(); installed <- installed.packages(lib.loc = '~/R'); print(installed[,c('Package', 'Version')])"

    - name: Run Tests
      run: |
        Rscript -e "devtools::load_all(); testthat::test_dir('tests/testthat')"