name: R Checks (no build yet)

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  Checking-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up R library environment using custom actions
      uses: r-lib/actions/setup-r@v2
  
    - name: Initialize renv (if necessary)
      run: |
        Rscript -e "if (!file.exists('renv.lock')) { renv::init(); renv::snapshot() }"

    - name: Install packages via renv
      run: |
        Rscript -e "renv::install(c('lintr', 'testthat', 'devtools'))"  # Install necessary packages via renv

    - name: Run Linter
      run: |
        Rscript -e "lintr::lint_package()"

    - name: Show installed R packages
      run: |
        Rscript -e "installed <- installed.packages(); print(installed[,c('Package', 'Version')])"

    - name: Run Tests
      run: |
        Rscript -e "devtools::load_all(); testthat::test_dir('tests/testthat')"