name: R Checks (no build yet)
on:
  pull_request:
    branches: [ "develop" ]

jobs:
  Checking-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up R library environment using custom actions
      uses: r-lib/actions/setup-r@v2
              
    - name: Test storing a variable
      run: |
        Rscript -e "a <- 3; b <- 5"
              
    - name: Test accessing variable
      run: |
        Rscript -e "cat(a+b)"

    - name: Cache R packages
      uses: actions/cache@v3
      with:
          path: ~/.cache/R/
          key: ${{ runner.os }}-r-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-
              
    - name: Install renv package
      run: |
        Rscript -e "install.packages('renv', repos = 'https://cran.rstudio.com/')"

    - name: Initialize renv and install basic R packages
      run: |
        Rscript -e "if (!file.exists('renv.lock')) { renv::init(); renv::install(c('lintr', 'testthat', 'devtools')); renv::snapshot() } else { renv::restore() }"

    - name: Show installed R packages
      run: |
        Rscript -e "installed <- installed.packages(); print(installed[,c('Package', 'Version')])"

    - name: Load all using devtools
      run: |
        Rscript -e "devtools::load_all()"
       
    - name: Run Linter
      run: |
          Rscript -e "lintr::lint_package()"

    - name: Initialize renv
      run: |
        Rscript -e "renv::init()"

    - name: Show installed R packages
      run: |
        Rscript -e "installed <- installed.packages(); print(installed[,c('Package', 'Version')])"

    - name: Run Tests
      run: |
        Rscript -e "testthat::test_package()