name: R Checks (no build yet)
on:
  pull_request:
    branches: [ "develop" ]

jobs:
  Checking-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Caching - hope this can improve github action runtime
      uses: actions/cache@v3
      with:
        path: ~/.cache/R/  # Cache the R library cache
        key: ${{ runner.os }}-r-${{ hashFiles('**/renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-r-

    - name: Set up R library environment using custom actions
      uses: r-lib/actions/setup-r@v2
  
    - name: Install and run Linter
      run: |
          Rscript -e "install.packages(c('lintr'), repos = 'https://cran.rstudio.com/');
          lintr::lint_package()"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev
        sudo apt-get install libharfbuzz-dev libfribidi-dev
        sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev

    - name: Set up R environment and install required R packages
      run: |
          Rscript -e "install.packages(c('renv', 'devtools', 'testthat'), repos = 'https://cran.rstudio.com/')"

    - name: Initialize renv
      run: |
        Rscript -e "renv::init()" # this needs curl
    
    - name: Show installed R packages
      run: |
        Rscript -e "installed <- installed.packages(); print(installed[,c('Package', 'Version')])"

    - name: Run Tests
      run: |
        Rscript -e "renv::status();
        devtools::load_all(); 
        testthat::test_dir('tests/testthat')"