name: Read and act based on previous commit message
on:
  pull_request:
    branches: [ "develop" ]

jobs:
  check-last-commit-message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Get previous commit message
      id: get_commit_message
      run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

    - name: Print commit message
      run: |
        echo "Previous commit message: '${{ env.COMMIT_MESSAGE }}'"

    - name: Set commit message as output
      id: set_commit_message
      run: echo "::set-output name=COMMIT_MESSAGE::${{ env.COMMIT_MESSAGE }}"

  conditional-job:
    runs-on: ubuntu-latest
    needs: check-commit-message
    if: contains(needs.check-commit-message.outputs.COMMIT_MESSAGE, 'Style code with styler')
    steps:
    - name: Run conditional step
      run: echo "This job runs because the commit message contains 'Style code with styler'."
