name: Improving Code Readability
on:
  pull_request:
    branches: [ "develop" ]

name: Improving Code Readability
on:
  pull_request:
    branches: [ "develop" ]

jobs:
  styling-linting-the-code:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up R library environment using custom actions
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
        sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev

    - name: Set locale and encoding
      run: |
        sudo locale-gen en_US.UTF-8
        export LANG=en_US.UTF-8
        export LC_ALL=en_US.UTF-8

    - name: Install Styler, Linter, and Roxygen2
      run: |
        Rscript -e "install.packages(c('lintr', 'styler', 'roxygen2'), repos = 'https://cran.rstudio.com/')"

    - name: Print R session info
      run: |
        Rscript -e "sessionInfo()"

    - name: Style R code
      run: |
        Rscript -e "styler::style_pkg(include_roxygen_examples = FALSE); warnings()"
    
    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Style code with styler' || echo "No changes to commit"
        git push origin HEAD:refs/heads/${{ github.head_ref }}

    - name: Run Linter
      run: |
        Rscript -e "lintr::lint_package()"